### ISSUE TITLE
Improvement: curl-less variant of parser

### ISSUE THREAD

**Issue by theyellow** [Googer/GymScraper#1]
I'm writing a curl-less AreaScraper implementation that's already working and extracts userId and session by itself. It's based on spring-web's RestTemplate. Because i've no IDEA, i 'mavenized' (wrote a pom.xml) and imported the project in Eclipse. So, too many changes for a PR, but if you're interested i'll glad to give you what you want.
I'm facing one problem in the moment: the paths includes/locdata.php and includes/it55nmsq9.php are dynamically set i think and i don't see how to get that information via java.

**Comment by theyellow** [comment]
Regarding the problem with the dynamical paths, is there any other way to get this information besides looking into Browser-dev-tools?

**Comment by ParadoxBoxx** [comment]
Unfortunately @Googer no longer maintains this because we try to stay out of legal trouble with scraping websites. Sounds like it's working great for you though!

**Comment by theyellow** [comment]
Ok, thanks for information and (template-)code! Works for now, so all good :)
